name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        type: string
        default: main

jobs:
  deploy:
    runs-on: runonflux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Ansible
        run: pip install ansible

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > flux-cert-1.key
          chmod 600 flux-cert-1.key

          cat >> ~/.ssh/config << EOF
          Host 10.100.0.172
              IdentityFile $(pwd)/flux-cert-1.key
              IdentitiesOnly yes
              StrictHostKeyChecking no
          EOF

      - name: Run Deployment
        run: |
          cd ansible
          ansible-playbook -i inventory.yaml deploy.yaml
